# Generated by Django 5.2.9 on 2025-12-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_veri_63cd6e_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
